// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqfC6Mwa3l7En_k16jfnjXF9eLuQWK34Q',
    appId: '1:286110052676:web:b8b412686d84ca41a42711',
    messagingSenderId: '286110052676',
    projectId: 'tangrad-8e049',
    authDomain: 'tangrad-8e049.firebaseapp.com',
    storageBucket: 'tangrad-8e049.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm8VLbg4VJ0dL26MpzsZigYYm0HLgxciw',
    appId: '1:286110052676:android:eddb9a9c2fec935fa42711',
    messagingSenderId: '286110052676',
    projectId: 'tangrad-8e049',
    storageBucket: 'tangrad-8e049.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD51afza5z5gVqqZX-uE0iclslhsbq8Qwg',
    appId: '1:286110052676:ios:5dbb3cb2890306bea42711',
    messagingSenderId: '286110052676',
    projectId: 'tangrad-8e049',
    storageBucket: 'tangrad-8e049.appspot.com',
    iosBundleId: 'com.tangrad.app',
  );

}